nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/api/': ~
